import * as anchor from "@coral-xyz/anchor";
import { AnchorWallet } from "@solana/wallet-adapter-react";

// Import your program IDL (generated by Anchor build)
// import idl from "./idl/dacit_program.json";

// Program ID - replace with your deployed program ID
const PROGRAM_ID = new anchor.web3.PublicKey(
  "DACITProg11111111111111111111111111111111111"
);

// Devnet endpoint
const DEVNET_ENDPOINT = "https://api.devnet.solana.com";

/**
 * Creates an Anchor Provider instance for interacting with the Solana network.
 *
 * @param wallet - The connected wallet instance
 * @returns Configured AnchorProvider
 */
export const getProvider = (wallet: AnchorWallet): anchor.AnchorProvider => {
  const connection = new anchor.web3.Connection(DEVNET_ENDPOINT, "confirmed");
  const provider = new anchor.AnchorProvider(connection, wallet, {
    preflightCommitment: "confirmed",
  });
  anchor.setProvider(provider);
  return provider;
};

/**
 * Creates an Anchor Program instance for the DACIT program.
 *
 * @param wallet - The connected wallet instance
 * @returns Configured Program instance
 *
 * @example
 * ```typescript
 * const program = getProgram(wallet);
 * await program.methods.stakeTokens(new BN(1000)).accounts({...}).rpc();
 * ```
 */
export const getProgram = (wallet: AnchorWallet): anchor.Program => {
  const provider = getProvider(wallet);

  // Note: In production, import the actual IDL generated by `anchor build`
  // return new anchor.Program(idl as anchor.Idl, PROGRAM_ID, provider);

  // Placeholder - replace with actual IDL import
  throw new Error(
    "Program IDL not configured. Run `anchor build` and import the generated IDL."
  );
};

/**
 * Derives a Program Derived Address (PDA) for a user's stake state.
 *
 * @param userPubkey - The user's public key
 * @returns [PDA, bump] tuple
 */
export const getStakeStatePDA = async (
  userPubkey: anchor.web3.PublicKey
): Promise<[anchor.web3.PublicKey, number]> => {
  return anchor.web3.PublicKey.findProgramAddressSync(
    [Buffer.from("stake"), userPubkey.toBuffer()],
    PROGRAM_ID
  );
};

/**
 * Derives a PDA for the emission schedule account.
 *
 * @returns [PDA, bump] tuple
 */
export const getEmissionSchedulePDA = async (): Promise<
  [anchor.web3.PublicKey, number]
> => {
  return anchor.web3.PublicKey.findProgramAddressSync(
    [Buffer.from("emission")],
    PROGRAM_ID
  );
};

/**
 * Derives a PDA for the program's token vault.
 *
 * @returns [PDA, bump] tuple
 */
export const getVaultPDA = async (): Promise<
  [anchor.web3.PublicKey, number]
> => {
  return anchor.web3.PublicKey.findProgramAddressSync(
    [Buffer.from("vault")],
    PROGRAM_ID
  );
};
