import * as anchor from "@coral-xyz/anchor";
import { AnchorWallet } from "@solana/wallet-adapter-react";

// Import your program IDL (generated by Anchor build)
// After running `anchor build`, import the generated IDL:
// import idl from "./idl/dacit_program.json";

// Program ID - replace with your deployed program ID after `anchor deploy`
const PROGRAM_ID = new anchor.web3.PublicKey(
  "DACITProg11111111111111111111111111111111111"
);

// Network endpoint - change to mainnet-beta for production
const DEVNET_ENDPOINT = "https://api.devnet.solana.com";

/**
 * Creates an Anchor Provider instance for interacting with the Solana network.
 *
 * @param wallet - The connected wallet instance
 * @returns Configured AnchorProvider
 */
export const getProvider = (wallet: AnchorWallet): anchor.AnchorProvider => {
  const connection = new anchor.web3.Connection(DEVNET_ENDPOINT, "confirmed");
  const provider = new anchor.AnchorProvider(connection, wallet, {
    preflightCommitment: "confirmed",
  });
  anchor.setProvider(provider);
  return provider;
};

/**
 * Creates an Anchor Program instance for the DACIT program.
 *
 * NOTE: This is a template. Before using:
 * 1. Run `anchor build` to generate the IDL
 * 2. Copy the IDL to frontend/utils/idl/dacit_program.json
 * 3. Import and use the actual IDL below
 *
 * @param wallet - The connected wallet instance
 * @returns Configured Program instance
 *
 * @example
 * ```typescript
 * const program = getProgram(wallet);
 * await program.methods.stakeTokens(new BN(1000)).accounts({...}).rpc();
 * ```
 */
export const getProgram = (wallet: AnchorWallet): anchor.Program => {
  const provider = getProvider(wallet);

  // TODO: Uncomment after generating IDL with `anchor build`
  // return new anchor.Program(idl as anchor.Idl, PROGRAM_ID, provider);

  // Placeholder - this will be replaced once the IDL is available
  console.warn(
    "Program IDL not yet configured. Run `anchor build` and import the generated IDL."
  );
  
  // Return a placeholder that throws on method calls
  return {
    programId: PROGRAM_ID,
    provider,
    methods: new Proxy({}, {
      get: () => () => {
        throw new Error(
          "Program IDL not configured. Run `anchor build` and import the generated IDL."
        );
      }
    })
  } as unknown as anchor.Program;
};

/**
 * Derives a Program Derived Address (PDA) for a user's stake state.
 *
 * @param userPubkey - The user's public key
 * @returns [PDA, bump] tuple
 */
export const getStakeStatePDA = (
  userPubkey: anchor.web3.PublicKey
): [anchor.web3.PublicKey, number] => {
  return anchor.web3.PublicKey.findProgramAddressSync(
    [Buffer.from("stake"), userPubkey.toBuffer()],
    PROGRAM_ID
  );
};

/**
 * Derives a PDA for the emission schedule account.
 *
 * @returns [PDA, bump] tuple
 */
export const getEmissionSchedulePDA = (): [anchor.web3.PublicKey, number] => {
  return anchor.web3.PublicKey.findProgramAddressSync(
    [Buffer.from("emission")],
    PROGRAM_ID
  );
};

/**
 * Derives a PDA for the program's token vault.
 *
 * @returns [PDA, bump] tuple
 */
export const getVaultPDA = (): [anchor.web3.PublicKey, number] => {
  return anchor.web3.PublicKey.findProgramAddressSync(
    [Buffer.from("vault")],
    PROGRAM_ID
  );
};
